spring:
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8084
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
server:
  port: 9090