spring:
  application:
    name: ms-users
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/parcial-back-end

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081

ms:
  keycloak:
    serverUrl: http://localhost:8080
    realm: parcial-back-end
    clientId: ms-user
    clientSecret: hOIPchDdv7MiaQfx69I3xtAbRCNDIT5X